# @title Manga Library FR - Colab Launcher
# @markdown Fill the form here or store secrets in the Colab Secrets panel.
# @markdown Secrets override form values.

API_ID = 0  # @param {type:"integer"}
API_HASH = ""  # @param {type:"string"}
BOT_TOKEN = ""  # @param {type:"string"}
OWNER_ID = 0  # @param {type:"integer"}

BOT_DATA_DIR = "/content/drive/MyDrive/MangaLibraryFR/data"  # @param {type:"string"}
MANGA_LANGUAGE = "fr"  # @param ["fr", "en", "es"]
MANGADEX_DATA_SAVER = False  # @param {type:"boolean"}
LOG_LEVEL = "INFO"  # @param ["DEBUG", "INFO", "WARNING", "ERROR"]

import os
import shutil
import signal
import subprocess
import sys
import threading
import time
from datetime import datetime
from pathlib import Path

REPO_URL = "https://github.com/vicMenma/manga-library-fr-bot.git"
BASE_DIR = Path("/content/manga-library-fr-bot")
PID_FILE = Path("/tmp/manga_library_fr_bot.pid")


def _log(level: str, msg: str) -> None:
    icons = {"INFO": "i", "OK": "+", "WARN": "!", "ERR": "x", "STEP": "*"}
    print(f"[{datetime.now().strftime('%H:%M:%S')}] {icons.get(level, '?')} {msg}", flush=True)


def _secret(name: str, default: str = "") -> str:
    try:
        from google.colab import userdata  # type: ignore

        value = userdata.get(name)
        if value is not None and str(value).strip():
            return str(value).strip()
    except Exception:
        pass
    return os.environ.get(name, default).strip()


def _secret_int(name: str, default: int = 0) -> int:
    try:
        return int(_secret(name, str(default)) or default)
    except Exception:
        return default


def _mount_drive() -> None:
    try:
        from google.colab import drive  # type: ignore

        _log("STEP", "Mounting Google Drive...")
        drive.mount("/content/drive", force_remount=False)
        _log("OK", "Google Drive mounted")
    except Exception as exc:
        _log("WARN", f"Drive mount skipped: {exc}")


def _clone_or_update_repo() -> Path:
    if BASE_DIR.exists() and (BASE_DIR / ".git").exists():
        _log("STEP", "Updating repository...")
        subprocess.run(["git", "-C", str(BASE_DIR), "pull", "--ff-only"], check=False)
        return BASE_DIR
    if BASE_DIR.exists():
        shutil.rmtree(BASE_DIR)
    _log("STEP", "Cloning repository...")
    subprocess.check_call(["git", "clone", "--depth=1", REPO_URL, str(BASE_DIR)])
    return BASE_DIR


def _install_python_packages(repo: Path) -> None:
    _log("STEP", "Installing Python packages...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "-e", str(repo)])
    _log("OK", "Python packages installed")


def _keep_alive() -> None:
    try:
        from IPython.display import Javascript, display

        display(
            Javascript(
                """
                setInterval(function() {
                    document.querySelector("#top-toolbar .colab-connect-button")?.click();
                    document.querySelector("colab-connect-button")?.shadowRoot?.querySelector("#connect")?.click();
                    document.querySelector("#ok")?.click();
                }, 60000);
                """
            )
        )
        _log("OK", "JS keep-alive injected")
    except Exception:
        _log("WARN", "JS keep-alive skipped")

    def _heartbeat() -> None:
        while True:
            time.sleep(300)
            print(f"\r[{datetime.now().strftime('%H:%M')}] <3", end="", flush=True)

    threading.Thread(target=_heartbeat, daemon=True).start()


def _clean_pid() -> None:
    if not PID_FILE.exists():
        return
    try:
        old_pid = int(PID_FILE.read_text(encoding="utf-8").strip())
        os.kill(old_pid, signal.SIGTERM)
        time.sleep(1)
    except Exception:
        pass
    PID_FILE.unlink(missing_ok=True)


def _collect_env() -> dict[str, str]:
    data_dir = _secret("BOT_DATA_DIR", BOT_DATA_DIR)
    Path(data_dir).mkdir(parents=True, exist_ok=True)
    return {
        "API_ID": str(_secret_int("API_ID", API_ID)),
        "API_HASH": _secret("API_HASH", API_HASH),
        "BOT_TOKEN": _secret("BOT_TOKEN", BOT_TOKEN),
        "OWNER_ID": str(_secret_int("OWNER_ID", OWNER_ID)),
        "BOT_DATA_DIR": data_dir,
        "MANGA_LANGUAGE": _secret("MANGA_LANGUAGE", MANGA_LANGUAGE),
        "MANGADEX_DATA_SAVER": _secret("MANGADEX_DATA_SAVER", str(MANGADEX_DATA_SAVER).lower()),
        "LOG_LEVEL": _secret("LOG_LEVEL", LOG_LEVEL),
        "PYTHONUNBUFFERED": "1",
    }


def _validate(env: dict[str, str]) -> None:
    missing = [k for k in ("API_ID", "API_HASH", "BOT_TOKEN", "OWNER_ID") if not env.get(k) or env.get(k) == "0"]
    if missing:
        raise SystemExit(f"Missing required credentials: {', '.join(missing)}")


def _write_env(repo: Path, env: dict[str, str]) -> None:
    lines = ["# Auto-generated by colab_launcher.py"]
    for key, value in env.items():
        if not value:
            continue
        escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'{key}="{escaped}"')
    (repo / ".env").write_text("\n".join(lines) + "\n", encoding="utf-8")
    _log("OK", ".env written")


def _run_bot(repo: Path, env: dict[str, str]) -> None:
    bot_env = {**os.environ, **env}
    process = subprocess.Popen(
        [sys.executable, "main.py"],
        cwd=str(repo),
        env=bot_env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )
    PID_FILE.write_text(str(process.pid), encoding="utf-8")
    _log("OK", "Starting bot...")
    print("-" * 50, flush=True)
    _log("INFO", f"Live logs below. Data dir: {env['BOT_DATA_DIR']}")

    try:
        assert process.stdout is not None
        for line in process.stdout:
            print(line, end="")
    finally:
        process.wait()
        PID_FILE.unlink(missing_ok=True)
        _log("WARN", f"Bot exited with code {process.returncode}")


def main() -> None:
    _mount_drive()
    repo = _clone_or_update_repo()
    _install_python_packages(repo)
    _keep_alive()
    _clean_pid()
    env = _collect_env()
    _validate(env)
    _write_env(repo, env)
    _log("OK", f"OWNER_ID={env['OWNER_ID']}")
    _log("OK", f"BOT_DATA_DIR={env['BOT_DATA_DIR']}")
    _log("OK", f"MANGA_LANGUAGE={env['MANGA_LANGUAGE']}")
    _run_bot(repo, env)


main()
